(()=>{
const API='https://bedixienygfeqtadzeng.supabase.co/functions/v1/axel-ai';
const KEY='orionix_axel_link_v1';
if(window.__ORIONIX_AXEL_LINK__)return;window.__ORIONIX_AXEL_LINK__=true;
const style=document.createElement('style');style.textContent=`#oax-fab{position:fixed;right:22px;bottom:22px;z-index:99999;width:58px;height:58px;border-radius:50%;border:1px solid #e8c86a;background:radial-gradient(circle,#fff4bc,#c8a24a 55%,#70561e);color:#171107;font:900 11px Cinzel,serif;letter-spacing:1px;box-shadow:0 0 22px rgba(232,200,106,.45);cursor:pointer}#oax-box{position:fixed;right:22px;bottom:92px;z-index:99998;width:min(390px,calc(100vw - 28px));height:520px;background:rgba(7,7,10,.98);border:1px solid rgba(232,200,106,.3);border-radius:14px;box-shadow:0 25px 90px #000;display:none;flex-direction:column;overflow:hidden;backdrop-filter:blur(18px)}#oax-box.on{display:flex}#oax-head{padding:13px 15px;border-bottom:1px solid rgba(232,200,106,.16);display:flex;align-items:center;justify-content:space-between;font:700 11px Cinzel,serif;color:#e8c86a;letter-spacing:2px}#oax-state{font:500 9px Cinzel,serif;color:#9e9278;letter-spacing:1px;margin-top:3px}#oax-msgs{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:9px}.oax-m{max-width:88%;padding:10px 12px;border-radius:9px;color:#eee4cf;font:15px 'Cormorant Garamond',serif;line-height:1.5;white-space:pre-wrap}.oax-u{align-self:flex-end;background:rgba(232,200,106,.12);border:1px solid rgba(232,200,106,.2)}.oax-a{align-self:flex-start;background:rgba(255,255,255,.04);border:1px solid rgba(232,200,106,.12)}#oax-form{display:flex;gap:7px;padding:10px;border-top:1px solid rgba(232,200,106,.16)}#oax-input{flex:1;min-width:0;background:#09090c;color:#eee4cf;border:1px solid rgba(232,200,106,.18);border-radius:8px;padding:10px;outline:0;font:15px 'Cormorant Garamond',serif}#oax-send{border:1px solid #e8c86a;background:#e8c86a;color:#171107;border-radius:8px;padding:0 13px;font:700 10px Cinzel,serif;cursor:pointer}.oax-x{background:none;border:0;color:#9e9278;font-size:20px;cursor:pointer}`;document.head.appendChild(style);
const box=document.createElement('div');box.id='oax-box';box.innerHTML='<div id="oax-head"><div>AXEL · AI LINK<div id="oax-state">Conectando con el núcleo…</div></div><button class="oax-x" id="oax-close">×</button></div><div id="oax-msgs"><div class="oax-m oax-a">Hola. Soy AXEL. Esta ventana usa el mismo núcleo seguro de ORIONIX.</div></div><form id="oax-form"><input id="oax-input" autocomplete="off" placeholder="Escribe a AXEL…"><button id="oax-send">→</button></form>';document.body.appendChild(box);const fab=document.createElement('button');fab.id='oax-fab';fab.textContent='AXEL';document.body.appendChild(fab);
const msgs=box.querySelector('#oax-msgs'),input=box.querySelector('#oax-input'),send=box.querySelector('#oax-send'),state=box.querySelector('#oax-state');let history=[];
function add(c,t){const d=document.createElement('div');d.className='oax-m '+(c==='user'?'oax-u':'oax-a');d.textContent=t;msgs.appendChild(d);msgs.scrollTop=msgs.scrollHeight;history.push({role:c==='user'?'user':'assistant',content:t})}
async function diagnose(){try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'test_keys'})});const j=await r.json();const ok=(j.results||[]).filter(x=>x.state==='OK');state.textContent=ok.length?`● ${ok.length} proveedor(es) operativo(s)`:'● núcleo conectado · revisar API keys';state.style.color=ok.length?'#65e6a0':'#ff7272'}catch{state.textContent='● sin conexión al núcleo';state.style.color='#ff7272'}}
box.querySelector('#oax-close').onclick=()=>box.classList.remove('on');fab.onclick=()=>{box.classList.toggle('on');if(box.classList.contains('on'))input.focus()};box.querySelector('#oax-form').onsubmit=async e=>{e.preventDefault();const q=input.value.trim();if(!q)return;input.value='';add('user',q);send.disabled=true;state.textContent='AXEL pensando…';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,provider:'auto',history:history.slice(-18)})});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||'Error del núcleo');add('assistant',j.answer||'Sin respuesta.');state.textContent=`${String(j.provider||'AXEL').toUpperCase()} · ${j.model||'modelo'}${j.failedOver?' · FAILOVER':''}`;state.style.color='#65e6a0'}catch(err){add('assistant','AXEL no pudo responder: '+err.message);state.textContent='Error de proveedor · ejecuta diagnóstico';state.style.color='#ff7272'}finally{send.disabled=false;input.focus()}};diagnose();
})();